# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'configureWindow.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_ConfigureWindow(object):
    def setupUi(self, ConfigureWindow):
        ConfigureWindow.setObjectName("ConfigureWindow")
        ConfigureWindow.resize(1024, 575)
        self.centralwidget = QtWidgets.QWidget(ConfigureWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.sliceWidget = SliceWidget(self.centralwidget)
        self.sliceWidget.setObjectName("sliceWidget")
        self.gridLayout.addWidget(self.sliceWidget, 0, 0, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.scrollArea = QtWidgets.QScrollArea(self.groupBox)
        self.scrollArea.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, -237, 350, 749))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.groupBox_6 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_6.setObjectName("groupBox_6")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_6)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.viewFatRadioButton = QtWidgets.QRadioButton(self.groupBox_6)
        self.viewFatRadioButton.setObjectName("viewFatRadioButton")
        self.verticalLayout_3.addWidget(self.viewFatRadioButton)
        self.viewWaterRadioButton = QtWidgets.QRadioButton(self.groupBox_6)
        self.viewWaterRadioButton.setObjectName("viewWaterRadioButton")
        self.verticalLayout_3.addWidget(self.viewWaterRadioButton)
        self.gridLayout_2.addWidget(self.groupBox_6, 2, 0, 1, 2)
        self.groupBox_3 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_4 = QtWidgets.QLabel(self.groupBox_3)
        self.label_4.setObjectName("label_4")
        self.gridLayout_3.addWidget(self.label_4, 3, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox_3)
        self.label_5.setObjectName("label_5")
        self.gridLayout_3.addWidget(self.label_5, 4, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.groupBox_3)
        self.label_6.setObjectName("label_6")
        self.gridLayout_3.addWidget(self.label_6, 5, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox_3)
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 1, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox_3)
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 2, 0, 1, 1)
        self.umbilicisInferiorSpinBox = QtWidgets.QSpinBox(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.umbilicisInferiorSpinBox.sizePolicy().hasHeightForWidth())
        self.umbilicisInferiorSpinBox.setSizePolicy(sizePolicy)
        self.umbilicisInferiorSpinBox.setMaximum(300)
        self.umbilicisInferiorSpinBox.setObjectName("umbilicisInferiorSpinBox")
        self.gridLayout_3.addWidget(self.umbilicisInferiorSpinBox, 1, 1, 1, 1)
        self.umbilicisSuperiorSpinBox = QtWidgets.QSpinBox(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.umbilicisSuperiorSpinBox.sizePolicy().hasHeightForWidth())
        self.umbilicisSuperiorSpinBox.setSizePolicy(sizePolicy)
        self.umbilicisSuperiorSpinBox.setMaximum(300)
        self.umbilicisSuperiorSpinBox.setObjectName("umbilicisSuperiorSpinBox")
        self.gridLayout_3.addWidget(self.umbilicisSuperiorSpinBox, 2, 1, 1, 1)
        self.umbilicisLeftSpinBox = QtWidgets.QSpinBox(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.umbilicisLeftSpinBox.sizePolicy().hasHeightForWidth())
        self.umbilicisLeftSpinBox.setSizePolicy(sizePolicy)
        self.umbilicisLeftSpinBox.setMaximum(300)
        self.umbilicisLeftSpinBox.setObjectName("umbilicisLeftSpinBox")
        self.gridLayout_3.addWidget(self.umbilicisLeftSpinBox, 3, 1, 1, 1)
        self.umbilicisRightSpinBox = QtWidgets.QSpinBox(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.umbilicisRightSpinBox.sizePolicy().hasHeightForWidth())
        self.umbilicisRightSpinBox.setSizePolicy(sizePolicy)
        self.umbilicisRightSpinBox.setMaximum(300)
        self.umbilicisRightSpinBox.setObjectName("umbilicisRightSpinBox")
        self.gridLayout_3.addWidget(self.umbilicisRightSpinBox, 4, 1, 1, 1)
        self.umbilicisCoronalSpinBox = QtWidgets.QSpinBox(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.umbilicisCoronalSpinBox.sizePolicy().hasHeightForWidth())
        self.umbilicisCoronalSpinBox.setSizePolicy(sizePolicy)
        self.umbilicisCoronalSpinBox.setMaximum(300)
        self.umbilicisCoronalSpinBox.setObjectName("umbilicisCoronalSpinBox")
        self.gridLayout_3.addWidget(self.umbilicisCoronalSpinBox, 5, 1, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox_3, 5, 0, 1, 2)
        self.groupBox_2 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_2.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_2.setSpacing(2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.noneRadioButton = QtWidgets.QRadioButton(self.groupBox_2)
        self.noneRadioButton.setObjectName("noneRadioButton")
        self.verticalLayout_2.addWidget(self.noneRadioButton)
        self.diaphragmRadioButton = QtWidgets.QRadioButton(self.groupBox_2)
        self.diaphragmRadioButton.setObjectName("diaphragmRadioButton")
        self.verticalLayout_2.addWidget(self.diaphragmRadioButton)
        self.umbilicisRadioButton = QtWidgets.QRadioButton(self.groupBox_2)
        self.umbilicisRadioButton.setObjectName("umbilicisRadioButton")
        self.verticalLayout_2.addWidget(self.umbilicisRadioButton)
        self.CATBoundsRadioButton = QtWidgets.QRadioButton(self.groupBox_2)
        self.CATBoundsRadioButton.setObjectName("CATBoundsRadioButton")
        self.verticalLayout_2.addWidget(self.CATBoundsRadioButton)
        self.gridLayout_2.addWidget(self.groupBox_2, 3, 0, 1, 2)
        self.groupBox_5 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_5.setObjectName("groupBox_5")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox_5)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_8 = QtWidgets.QLabel(self.groupBox_5)
        self.label_8.setObjectName("label_8")
        self.gridLayout_4.addWidget(self.label_8, 1, 0, 1, 1)
        self.diaphragmAxialSpinBox = QtWidgets.QSpinBox(self.groupBox_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.diaphragmAxialSpinBox.sizePolicy().hasHeightForWidth())
        self.diaphragmAxialSpinBox.setSizePolicy(sizePolicy)
        self.diaphragmAxialSpinBox.setMaximum(300)
        self.diaphragmAxialSpinBox.setObjectName("diaphragmAxialSpinBox")
        self.gridLayout_4.addWidget(self.diaphragmAxialSpinBox, 1, 1, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox_5, 4, 0, 1, 2)
        self.groupBox_4 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout_5.setContentsMargins(5, 5, 5, 5)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.CATBoundsRemoveButton = QtWidgets.QPushButton(self.groupBox_4)
        self.CATBoundsRemoveButton.setObjectName("CATBoundsRemoveButton")
        self.gridLayout_5.addWidget(self.CATBoundsRemoveButton, 1, 1, 1, 1)
        self.CATBoundsAddButton = QtWidgets.QPushButton(self.groupBox_4)
        self.CATBoundsAddButton.setObjectName("CATBoundsAddButton")
        self.gridLayout_5.addWidget(self.CATBoundsAddButton, 1, 0, 1, 1)
        self.CATBoundsTableWidget = QtWidgets.QTableWidget(self.groupBox_4)
        self.CATBoundsTableWidget.setDragDropMode(QtWidgets.QAbstractItemView.NoDragDrop)
        self.CATBoundsTableWidget.setDefaultDropAction(QtCore.Qt.MoveAction)
        self.CATBoundsTableWidget.setAlternatingRowColors(True)
        self.CATBoundsTableWidget.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.CATBoundsTableWidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.CATBoundsTableWidget.setObjectName("CATBoundsTableWidget")
        self.CATBoundsTableWidget.setColumnCount(3)
        self.CATBoundsTableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.CATBoundsTableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.CATBoundsTableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.CATBoundsTableWidget.setHorizontalHeaderItem(2, item)
        self.CATBoundsTableWidget.horizontalHeader().setVisible(True)
        self.CATBoundsTableWidget.verticalHeader().setVisible(False)
        self.gridLayout_5.addWidget(self.CATBoundsTableWidget, 0, 0, 1, 2)
        self.gridLayout_2.addWidget(self.groupBox_4, 6, 0, 1, 2)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 10, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 1, 0, 1, 1)
        self.sliceSlider = QtWidgets.QSlider(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sliceSlider.sizePolicy().hasHeightForWidth())
        self.sliceSlider.setSizePolicy(sizePolicy)
        self.sliceSlider.setOrientation(QtCore.Qt.Horizontal)
        self.sliceSlider.setObjectName("sliceSlider")
        self.gridLayout_2.addWidget(self.sliceSlider, 1, 1, 1, 1)
        self.saveButton = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.saveButton.setObjectName("saveButton")
        self.gridLayout_2.addWidget(self.saveButton, 9, 0, 1, 2)
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.panButton = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.panButton.setObjectName("panButton")
        self.gridLayout_6.addWidget(self.panButton, 0, 1, 1, 1)
        self.homeButton = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.homeButton.setObjectName("homeButton")
        self.gridLayout_6.addWidget(self.homeButton, 0, 0, 1, 1)
        self.zoomButton = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.zoomButton.setObjectName("zoomButton")
        self.gridLayout_6.addWidget(self.zoomButton, 0, 2, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout_6, 8, 0, 1, 2)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)
        self.gridLayout.addWidget(self.groupBox, 0, 1, 1, 1)
        self.gridLayout.setColumnStretch(0, 5)
        self.gridLayout.setColumnStretch(1, 3)
        ConfigureWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(ConfigureWindow)
        self.statusbar.setObjectName("statusbar")
        ConfigureWindow.setStatusBar(self.statusbar)

        self.retranslateUi(ConfigureWindow)
        QtCore.QMetaObject.connectSlotsByName(ConfigureWindow)

    def retranslateUi(self, ConfigureWindow):
        _translate = QtCore.QCoreApplication.translate
        ConfigureWindow.setWindowTitle(_translate("ConfigureWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("ConfigureWindow", "Controls"))
        self.groupBox_6.setTitle(_translate("ConfigureWindow", "View"))
        self.viewFatRadioButton.setText(_translate("ConfigureWindow", "Fat Only"))
        self.viewWaterRadioButton.setText(_translate("ConfigureWindow", "Water Only"))
        self.groupBox_3.setTitle(_translate("ConfigureWindow", "Umbilicis"))
        self.label_4.setText(_translate("ConfigureWindow", "Left: "))
        self.label_5.setText(_translate("ConfigureWindow", "Right: "))
        self.label_6.setText(_translate("ConfigureWindow", "Coronal: "))
        self.label_2.setText(_translate("ConfigureWindow", "Inferior: "))
        self.label_3.setText(_translate("ConfigureWindow", "Superior: "))
        self.groupBox_2.setTitle(_translate("ConfigureWindow", "Editing"))
        self.noneRadioButton.setText(_translate("ConfigureWindow", "None"))
        self.diaphragmRadioButton.setText(_translate("ConfigureWindow", "Diaphragm"))
        self.umbilicisRadioButton.setText(_translate("ConfigureWindow", "Umbilicis"))
        self.CATBoundsRadioButton.setText(_translate("ConfigureWindow", "CAT Bounds"))
        self.groupBox_5.setTitle(_translate("ConfigureWindow", "Diaphragm"))
        self.label_8.setText(_translate("ConfigureWindow", "Axial: "))
        self.groupBox_4.setTitle(_translate("ConfigureWindow", "CAT Bounds"))
        self.CATBoundsRemoveButton.setText(_translate("ConfigureWindow", "Remove Line"))
        self.CATBoundsAddButton.setText(_translate("ConfigureWindow", "Add Line"))
        item = self.CATBoundsTableWidget.horizontalHeaderItem(0)
        item.setText(_translate("ConfigureWindow", "Axial"))
        item = self.CATBoundsTableWidget.horizontalHeaderItem(1)
        item.setText(_translate("ConfigureWindow", "Posterior"))
        item = self.CATBoundsTableWidget.horizontalHeaderItem(2)
        item.setText(_translate("ConfigureWindow", "Anterior"))
        self.label_7.setText(_translate("ConfigureWindow", "Slice: "))
        self.saveButton.setText(_translate("ConfigureWindow", "Save"))
        self.panButton.setText(_translate("ConfigureWindow", "Pan"))
        self.homeButton.setText(_translate("ConfigureWindow", "Home"))
        self.zoomButton.setText(_translate("ConfigureWindow", "Zoom"))

from sliceWidget import SliceWidget
